name: Your New Jekyll Site
description: Blogging about stuffs
meta_description: "Hello, "

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: "/jungwonchae"
domain_name: "http://jungwonchae.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "http://jungwonchae.github.io"
author: "jungwon"

# Disqus config
disqus-shortname: ""
